Implementation of new design and local cache to prevent github requests.
OpenDevUFCG/opendevufcg.org pull request #165
Opened 2021-04-30 20:41 UTC by felipedaf

#### Qual o objetivo dessa Pull Request?
Finalizacao da implementacao inicial do novo design proposto.
Achei um bug no sistema: O github limita para 60 requests para a API, e se o usuario fizer o refresh varias vezes vai chegar ao limite de requests e consequentemente bloqueando novas requests.

#### Que problema está resolvendo?
Para resolver isso implementei um cache local para evitar com que essa request chegue na API do github.
Mas recomendo fazer uma modificacao para requests autenticados e aumentar o limite de requests possiveis.

#### Como pode ser manualmente testado?
Pode dar refresh varias vezes na pagina atual do deploy reiniciando o cache, vai chegar uma hora que as requisicoes ao github serao bloqueadas e os dados dos membros nao serao carregados.

#### Screenshots
Deploy na vercel: https://opendevufcg-org.vercel.app/

#### Tipos de mudanças

* [x] Conserta um bug
* [x] Nova funcionalidade
* [x] Refatoração de código
* [ ] Atualiza documentação

2021-04-30 21:02 UTC, jessescn commented on docs/home/css/styles.css
> +.section-split {
Acabou que ficou meio apertado as seções, tenta adicionar um height: 40vh e vê o que acha

2021-04-30 21:02 UTC, jessescn commented on docs/home/css/styles.css
> +  width: 90px;
Tenta aumentar para 12.5rem o height e o width

2021-04-30 21:04 UTC, jessescn commented on docs/home/css/styles.css
> +  width: 50px;
Tenta aumentar o height e o width para 4.37rem, além disso, tu poderia adicionar um efeito ao passar o mouse por cima, por exemplo, aumentar um pouco

2021-04-30 21:05 UTC, jessescn commented on docs/home/css/styles.css
> +  max-width: 290px;
remove o max-width e o max-height, deixa só o height: 90%, se quiser alinhar tu pode colocar um flex e colocar justify-content: center

2021-04-30 21:07 UTC, jessescn commented on docs/home/css/styles.css
> +  font-size: 12px;
Aumenta para 1rem, creio que a letra esteja muito pequena (além de que essa fonte não ajuda nesse caso)

2021-04-30 21:08 UTC, jessescn commented on docs/home/css/styles.css
> +  margin: 0;
Adiciona um box-sizing: border-box

2021-04-30 21:09 UTC, jessescn commented on docs/home/css/styles.css
sugiro adicionar isso aqui para trabalhar com responsividade
```suggestion
 @media (max-width: 1080px){
    html {
        font-size: 93.75%;
    }
  }
  @media (max-width: 720px){
    html {
        font-size: 87.5%;
    }
  }
```

2021-04-30 21:10 UTC, jessescn commented on docs/home/css/styles.css
> +.discover-button {
Tanto nesse como nos outros botões eu aconselho adicionar o cursor: pointer e se quiser alguma animação simples usando transform: scale quando passar o mouse por cima

2021-04-30 21:15 UTC, jessescn commented on docs/home/js/app.js
> +  memberLink.href = url_github
adiciona memberLink.target = "_blank" para que o usuário não saia da página quando clicar no link

2021-05-09 19:49 UTC, FelipeAmorimFerreira commented on docs/home/css/styles.css
> +  max-width: 290px;
O max height e width são necessários para ter o scroll.

2021-05-13 13:59 UTC, jessescn requested changes
Muito bom, eu coloquei umas correções mais diretas agora para agilizar um pouco, tenta elas e vê o que tu acha. Outra coisa que eu recomendaria é criar varíaveis para as cores no css, se tiver dúvidas como fazer tem esse [link](https://developer.mozilla.org/pt-BR/docs/Web/CSS/var()) que explica como. De resto muito obrigado pelo esforço e contribuição 😄

2021-05-13 13:59 UTC, jessescn commented on docs/home/css/styles.css
> +  font-size: 0.8rem;
```suggestion
  font-size: 1rem;
```

2021-05-13 13:59 UTC, jessescn commented on docs/home/css/styles.css
> +  display: grid;
```suggestion
  width: 40%;
  display: grid;
```

2021-05-13 13:59 UTC, jessescn commented on docs/home/css/styles.css
> +  grid-template-columns: 1fr 1fr;
```suggestion
  grid-template-columns: 1fr 1fr;
  grid-gap: 7px;
```

2021-05-13 13:59 UTC, jessescn commented on docs/home/css/styles.css
> +  max-height: 190px;
```suggestion
  max-width: 500px;
  max-height: 400px;
```

2021-05-13 13:59 UTC, jessescn commented on docs/home/css/styles.css
> +  height: 3rem;
```suggestion
  width: 4rem;
  height: 4rem;
```

2021-05-13 13:59 UTC, jessescn commented on docs/home/css/styles.css
> +  height: 5.5rem;
```suggestion
  border-radius: 3px;
  transition: 0.2s ease;
```

2021-05-13 13:59 UTC, jessescn commented on docs/home/css/styles.css
```suggestion
.project:hover {
  transform: scale(1.04);
}
```

2021-05-13 13:59 UTC, jessescn commented on docs/home/css/styles.css
> +  transform: scale(.85, 1);
```suggestion
  transition: .2s ease;
```

2021-05-13 13:59 UTC, jessescn commented on docs/home/css/styles.css
```suggestion
.default-button:hover {
  transform: scale(1.04);
  background-color: #fff;
  color: #343587;
}
```

2021-05-13 13:59 UTC, jessescn commented on docs/home/css/styles.css
> +  height: 42px;
```suggestion
  padding: 10px 25px;
```

2021-05-13 13:59 UTC, jessescn commented on docs/home/css/styles.css
```suggestion
  section {
    padding: 0 15%;
  }

  .discord-section {
    padding: 0;
  }

  .join-community {
    text-align: left;
  }

  .join-community-call {
    flex-direction: column;
    align-items: flex-start;
    padding: 40px 0; 
  }

  .join-community-phrase {
      text-align: left;
      width: 100%;
      padding: 0;
      margin-bottom: 1rem;
    }
  
  .projects {
    width: 100%;
  }
  
    .maintainers {
    width: 100%;
    max-width: 100%;
  }

  .join-discord {
    font-size: 2rem;
  }

  .community-call-label {
    width: 100%;
    font-size: 1.3rem;
  }
```

2021-05-13 13:59 UTC, jessescn commented on docs/home/css/styles.css
> +  }
```suggestion
  .join-discord-call img {
    height: 60px;
  }
```

2021-05-13 13:59 UTC, jessescn commented on docs/home/css/styles.css
> +  }
```suggestion
```

2021-05-13 13:59 UTC, jessescn commented on docs/index.html
> +        <section class="section-split">
```suggestion
        <section class="section-split  discord-section">
```

2021-10-28 17:24 UTC, merged