Feat/socials
OpenDevUFCG/opendevufcg.org pull request #184
Opened 2022-09-08 00:03 UTC by jpalvesl

#### Qual o objetivo dessa Pull Request?
 Adicionar o componente de redes sociais.

#### Que problema está resolvendo?
 #174 

#### Como pode ser manualmente testado?
Acessando a minha branch local `feat/socials` já é possível usar o componente da seguinte forma:

```js
<Socials
    title="Acesse nosso github!"
    mediaName="Github"
    description="Aqui você pode acessar todos os nossos repositórios. Não esqueça de deixar uma star em cada um!"
    icon={githubIcon}
/>
```

#### Screenshots

![Captura de tela de 2022-09-07 20-55-52](https://user-images.githubusercontent.com/47665775/189003687-5ced3b34-72cb-4f5f-b58d-3bf8076118d3.png)

#### Tipos de mudanças

* [ ] Conserta um bug
* [x] Nova funcionalidade
* [ ] Refatoração de código
* [ ] Atualiza documentação

2022-09-08 14:39 UTC, RodrigoEC requested changes
João parabens pela implementação!! FIcou muito legal. Apontei algumas mudanças e pensei nesse design pra o mobile, ja que hoje em dia o design que está não funciona em telas mobile

![image](https://user-images.githubusercontent.com/42751604/189145863-e05248a8-cd66-49cf-826c-e094e67a7630.png)

2022-09-08 14:39 UTC, RodrigoEC commented on src/components/Socials/styles.js
> +`
```suggestion
  overflow: hidden
`
```

Com essa propriedade você não precisa adicionar o border-radius no ícone 😄 o que evita você ter que trocar isso em dois lugares

2022-09-08 14:39 UTC, RodrigoEC commented on src/components/Socials/styles.js
> +  font-family: 'Roboto', sans-serif;
Pode tirar esse `font-family`, nós vamos definir a fonte de forma global ;)

2022-09-08 14:39 UTC, RodrigoEC commented on src/components/Socials/styles.js
> +  margin-right: 26px;
Acho bom trocar o margin-right e o margin-left por:

```suggestion
  padding: 1rem;
```

2022-09-08 14:39 UTC, RodrigoEC commented on src/components/Socials/styles.js
> +  border-radius: 0 8px 8px 0;
```suggestion
```

2022-09-08 14:39 UTC, RodrigoEC commented on src/components/Socials/styles.js
> +  height: 216px;
acredito que você não precise colocar o height
```suggestion
```

2022-09-08 14:39 UTC, RodrigoEC commented on src/components/Socials/styles.js
> +  width: 216px;
```suggestion
  width: 13.5rem;
```

2022-09-08 14:39 UTC, RodrigoEC commented on src/components/Socials/styles.js
> +export const IconContainer = styled.div`
Pelo q eu entendi e testei tu pode retirar esse `IconContainer`

2022-09-08 14:39 UTC, RodrigoEC commented on src/components/Socials/index.js
> +function Socials({ title, mediaName, description, icon, ...props}) {
Tu pode colocar a funcionalidade de clicar no componente e redirecionar pra o link passado como prop?

Link do github: https://github.com/orgs/OpenDevUFCG;
Link do discord: https://discord.gg/FD9X3rngEz

2022-09-08 14:39 UTC, RodrigoEC commented on src/components/Socials/styles.js
> +  font-size: 16px;
```suggestion
  font-size: 16px;
  letter-spacing: 0.125rem;
```

2022-09-08 16:47 UTC, jpalvesl commented
As alterações no componente foram, feitas.
Está faltando apenas fazer com que o componente fique da forma proposta no mobile.

2022-09-08 16:50 UTC, RodrigoEC commented
> As alterações no componente foram, feitas. Está faltando apenas fazer com que o componente fique da forma proposta no mobile.

Ta certo! Quando tu fizer tu marca pra eu re-revisar pff 😄

2022-09-09 12:51 UTC, jpalvesl commented
@RodrigoEC as alterações no componente com a sugestão de como ele deve ficar no mobile foi feita.

![Captura de tela de 2022-09-09 09-48-11](https://user-images.githubusercontent.com/47665775/189353729-b8b0e34c-af57-412c-9ad7-567298d65585.png)

2022-09-09 13:53 UTC, RodrigoEC requested changes
Tamo terminando! kkkkkkk Ta tudo muito top, apontei só umas estilizações finais bem específicas! :)

2022-09-09 13:53 UTC, RodrigoEC commented on src/components/Socials/styles.js
> +  width: 549px;
```suggestion
  max-width: 35rem;
```

2022-09-09 13:53 UTC, RodrigoEC commented on src/components/Socials/styles.js
> +  height: 216px;
```suggestion
```

2022-09-09 13:53 UTC, RodrigoEC commented on src/components/Socials/styles.js
> +    height: 480px;
```suggestion
```

2022-09-09 13:53 UTC, RodrigoEC commented on src/components/Socials/styles.js
> +    width: 216px;
```suggestion
    width: 18rem;
```

2022-09-09 13:53 UTC, RodrigoEC commented on src/components/Socials/styles.js
> +    width: 216px;
```suggestion
    width: 18rem;
```

2022-09-09 13:53 UTC, RodrigoEC commented on src/components/Socials/styles.js
> +  width: 13.5rem;
```suggestion
  width: 100%;
```

2022-09-09 13:53 UTC, RodrigoEC commented on src/components/Socials/styles.js
> +  margin-top: 41px;
```suggestion
  margin: 2rem 0;
```

2022-09-09 13:53 UTC, RodrigoEC commented on src/components/Socials/styles.js
> +  margin-top: 30px;
```suggestion
  margin-top: 1rem;
```

2022-09-09 13:53 UTC, RodrigoEC commented on src/components/Socials/styles.js
> +  display: flex;
```suggestion
  display: flex;
  align-items: center;
```

2022-09-09 14:17 UTC, jpalvesl commented
> Tamo terminando! kkkkkkk Ta tudo muito top, apontei só umas estilizações finais bem específicas! :)

kkkkkk, tranquilo, fiz as alterações aqui

2022-09-09 14:43 UTC, RodrigoEC commented
Tudo certinho!! Obrigado pela contribuição @jpalvesl! Depois vou cadastrar mais issues pra montar as páginas e caso tu queira contribuir de novo pode ficar a vontade ❤️

2022-09-09 14:45 UTC, merged

2022-09-09 14:45 UTC, jpalvesl commented
> Tudo certinho!! Obrigado pela contribuição @jpalvesl! Depois vou cadastrar mais issues pra montar as páginas e caso tu queira contribuir de novo pode ficar a vontade heart

Pode deixar, vou querer sim :)