Feat/utils components
OpenDevUFCG/opendevufcg.org pull request #185
Opened 2022-09-12 16:53 UTC by emanamoura

#### Qual o objetivo dessa Pull Request?

- Criação do componente de membros juntamente com o seu tooltip.
- Criação do componente de título de uma seção.
#### Que problema está resolvendo?

#170 

#### Como pode ser manualmente testado?
Basta colocar os componentes SectionTitle ou o componente Member em qualquer função que renderize um JSX.
#### Screenshots

![image](https://user-images.githubusercontent.com/94456436/189711599-d952bd82-ca32-41c6-9a0e-f8ab09cc3695.png)
![image](https://user-images.githubusercontent.com/94456436/189711648-65010f27-6b23-449d-af39-76163906b4b8.png)
![image](https://user-images.githubusercontent.com/94456436/189711703-0b80e375-d2e5-4d59-9b78-35cb2070d09e.png)

#### Tipos de mudanças

* [ ] Conserta um bug
* [x] Nova funcionalidade
* [ ] Refatoração de código
* [ ] Atualiza documentação

2022-09-13 14:10 UTC, RodrigoEC requested changes
@emanamoura tu ta arrasando com as contribuições! 🚀 Comentei algumas sugestões pra mudança. Além disso, lembra de atualizar a tua branch com a develop 😄

2022-09-13 14:10 UTC, RodrigoEC commented on src/components/SectionTitle/style.js
> +export const Title = styled.h1`
Pensando aqui, acho que a gente pode usar só esse Title como o componente de título, não precisando usar ele no SectionTitle, ele pode ser o SectionTitle

```suggestion
export const SectionTitle = styled.h2`
```
⚠️ OBS: mudei pra `h2` pra que leitores de tela identifiquem os titulos da seção não como o título principal da página, mas como o secundário.


Dessa forma, tu pode o conteúdo desse arquivo pra o arquivo `src/components/index.js`

2022-09-13 20:13 UTC, emanamoura commented on src/components/Member/style.js
> +    position: relative;
Preciso deixar o display como inline-block, pois dessa forma, se não o fizer, não consigo colocar uma medida para o componente de maneira personalizada.

2022-09-13 21:43 UTC, RodrigoEC commented on src/components/Member/style.js
> +    position: relative;
Entendii, realmente :)

2022-09-14 14:13 UTC, RodrigoEC approved these changes
Você arrasou demaaaaaais @emanamoura obrigado pela contribuição novamenteee! Parabens 😄🚀

2022-09-14 14:13 UTC, merged

2022-09-14 14:21 UTC, emanamoura commented
> Você arrasou demaaaaaais @emanamoura obrigado pela contribuição novamenteee! Parabens 😄🚀

Obrigado !!!!!! Eu que agradeço, você é um revisador bom demais !