Develop
OpenDevUFCG/opendevufcg.org pull request #186
Opened 2022-09-15 17:14 UTC by joaovictorsl

#### Qual o objetivo dessa Pull Request?
- Removi código que considerei redundante em routes.js
- Removi console.log de members que provavelmente foi utilizado para testes e esquecido
- Adicionei a página de eventos
- Adicionei o card de eventos

#### Que problema está resolvendo?
#181

#### Como pode ser manualmente testado?
Inicie a aplicação e entre na página de eventos

#### Screenshots
![eventspage](https://user-images.githubusercontent.com/79459468/190468451-c241c004-3d4f-45d0-87e1-44c607561ff8.png)

#### Tipos de mudanças

* [ ] Conserta um bug
* [x] Nova funcionalidade
* [x] Refatoração de código
* [ ] Atualiza documentação

2022-09-15 17:18 UTC, joaovictorsl commented
Opa, @RodrigoEC, eu fiz o card mas não cuidei de responsividade. Como não tem o esqueleto eu não tive ideia de como testaria a responsividade do card 😕.

2022-09-15 17:24 UTC, RodrigoEC commented
OOii @joaovictorsl, então a ideia seria implementar esse card aqui ó:

![image](https://user-images.githubusercontent.com/42751604/190469954-c9b8c596-4f3f-4fe3-8195-097f9a8d824f.png)

Eu acho que como o design que tu seguiu e esse não são muito diferentes, na verdade eles são bem parecidos, acho que fica mais tranquilo de refatorar. 

Sobre a responsividade, realmente esse card grandão que tu fez fica dificil de fazer a responsividade, porém acredito que esse card menorzinho ele ja caiba certinho numa tela mobile, diminuindo só o tamanho da imagem msm, pra telas menores

2022-09-15 21:07 UTC, joaovictorsl commented
![novo](https://user-images.githubusercontent.com/79459468/190508918-e1035091-3e09-4140-9d0d-fa94391ce48e.png)

2022-09-15 22:14 UTC, RodrigoEC requested changes
@joaovictorsl revisei visse! Tem algumas alterações importantes como a adição do defaultProps e propTypes e o uso de rem ao inves de % e vw 😄.

Quanto a responsividade ela funciona certinho com o tamanho que ta esse card. 🚀

2022-09-16 01:16 UTC, RodrigoEC requested changes

2022-09-16 01:16 UTC, RodrigoEC commented on src/components/EventCard/index.js
> +    </Card>
```suggestion
    <Card>
      <UpperRow>
        <ImageSide>
          <EventImage src={org_image} alt={name} />
        </ImageSide>
        <InfoSide>
          <Title>{name}</Title>
          <Date>Data do evento - {init_date}</Date>
        </InfoSide>
      </UpperRow>
      <LowerRow>
        <Description>{description}</Description>
      </LowerRow>
    </Card>
```

2022-09-16 01:16 UTC, RodrigoEC commented on src/components/EventCard/index.js
> +  description = "O Andromedev é um evento organizado pela organização estudantil OpenDevUFCG com o intuito de incentivar a participação de estudantes da Universidade Federal de Campina Grande (UFCG)
Seria melhor colocar os props padrão no final do arquivo usando EventCard.defaultProps como está no arquivo do componente [Carousel](https://github.com/OpenDevUFCG/opendevufcg.org/blob/develop/src/components/Carousel/index.js)

```suggestion
export const EventCard = ({ name, init_date, end_date, org_image
```

2022-09-16 01:16 UTC, RodrigoEC commented on src/components/EventCard/index.js
> +}
Adiciona por favor o `EventCard.propTypes`, pra tu ter referencia, usa o arquivo do componente [Carousel](https://github.com/OpenDevUFCG/opendevufcg.org/blob/develop/src/components/Carousel/index.js)

2022-09-16 01:16 UTC, RodrigoEC commented on src/components/EventCard/style.js
> +`;
Aqui a gente pode resumir esse Card em:

```suggestion
export const Card = styled.div`
  display: flex;
  flex-direction: column;
  max-width: 24rem;
  width: 100%;
  border-radius: 8px;
  background-color: #f9f9f9;
  box-shadow: 0px 4px 8px #00000025;
  padding: 0.75rem;
  box-sizing: border-box;
`;
```

2022-09-16 01:16 UTC, RodrigoEC commented on src/components/EventCard/style.js
> +`;
É bom evitar padding em porcentagem. Nesse caso podemos tirar o padding por que adicionamos no Card um padding geral.

```suggestion
export const UpperRow = styled.div`
display: flex;
`;
```

2022-09-16 01:16 UTC, RodrigoEC commented on src/components/EventCard/style.js
> +padding: 0 2.5% 2.5% 2.5%;
```suggestion
```

2022-09-16 01:16 UTC, RodrigoEC commented on src/components/EventCard/style.js
> +`;
No caso do ImageSide, podemos retira-lo adicionando no EventImage o atributo de margin :)

```suggestion
export const EventImage = styled.img`
  border-radius: 8px;
  border: 2px solid rgba(52, 53, 135, 0.3);
  max-width: 10rem;
  margin: 0 8px 8px 0;
`;
```

2022-09-16 01:16 UTC, RodrigoEC commented on src/components/EventCard/style.js
> +padding: .4vw;
```suggestion
```

2022-09-16 01:16 UTC, RodrigoEC commented on src/components/EventCard/style.js
> +`;
É bom mudar a medida vw por px ou rem

```suggestion
export const Title = styled.h1`
  font-weight: 700;
  letter-spacing: 0.125em;
  color: #393a6e;

  font-size: 16px;
  line-height: 1.25rem;
`;
```

2022-09-16 01:16 UTC, RodrigoEC commented on src/components/EventCard/style.js
> +`;
```suggestion
export const Date = styled.h2`
  font-weight: 700;
  letter-spacing: 0.125em;
  color: #7e7fc1;

  font-size: 12px;
  line-height: 1vw;
`;

export const Description = styled.span`
  font-weight: 400;
  font-size: 14px;
  line-height: 1.25rem;
  text-align: justify;
  color: #2a2a2a;
`;
```

2022-09-16 01:16 UTC, RodrigoEC commented on src/pages/Events/style.js
> +`;
Ao inves de implementar o Title nesse arquivo seria melhor utilizar o `SectionTitle` no arquivo ### **src/components/index.js**

```suggestion

```

2026-07-21 19:38 UTC, closed without merging